apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["musti-apps/mariadb"]'
    management.cattle.io/ui-managed: "true"
  name: mariadb
  namespace: musti-apps
spec:
  clusterIP: 10.43.66.149
  clusterIPs:
  - 10.43.66.149
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: mariadb
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-musti-apps-mariadb
  sessionAffinity: None
  type: ClusterIP
