apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"port":30001,"protocol":"TCP","serviceName":"musti-apps:meiraaccessories-nodeport","allNodes":true}]'
    field.cattle.io/targetWorkloadIds: '["musti-apps/meiraaccessories"]'
    management.cattle.io/ui-managed: "true"
  name: meiraaccessories-nodeport
  namespace: musti-apps
spec:
  clusterIP: 10.43.126.28
  clusterIPs:
  - 10.43.126.28
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: wordpress
    nodePort: 30001
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-musti-apps-meiraaccessories
  sessionAffinity: None
  type: NodePort
