apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["musti-apps/meiraaccessories"]'
    management.cattle.io/ui-managed: "true"
  name: meiraaccessories
  namespace: musti-apps
spec:
  clusterIP: 10.43.136.135
  clusterIPs:
  - 10.43.136.135
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: mariadb
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: wordpress
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-musti-apps-meiraaccessories
  sessionAffinity: None
  type: ClusterIP
