apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"port":30002,"protocol":"TCP","serviceName":"musti-apps:weather-api-nodeport","allNodes":true}]'
    field.cattle.io/targetWorkloadIds: '["musti-apps/weather-api"]'
    management.cattle.io/ui-managed: "true"
  name: weather-api-nodeport
  namespace: musti-apps
spec:
  clusterIP: 10.43.103.214
  clusterIPs:
  - 10.43.103.214
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: musti-api
    nodePort: 30002
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-musti-apps-weather-api
  sessionAffinity: None
  type: NodePort
